"""Guides users on configuring Claude Desktop in 3P gateway mode."""


def print_guide(base_url: str, port: int) -> None:
    """Print step-by-step instructions for Claude Desktop 3P setup."""
    print()
    print("  ── Claude Desktop 3P Gateway Setup ──")
    print()
    print("  1. Open Claude Desktop (do NOT sign in)")
    print("  2. Enable Developer Mode:")
    print("     macOS: Help → Troubleshooting → Enable Developer Mode")
    print("     Windows: ☰ → Help → Troubleshooting → Enable Developer Mode")
    print("  3. Open config window:")
    print("     Developer → Configure third-party inference")
    print("  4. Connection tab — enter:")
    print("     Inference provider:  Gateway")
    print(f"     Gateway base URL:    {base_url}")
    print(f"     API key:             (any value — the proxy handles auth)")
    print("     Auth scheme:         bearer")
    print("  5. Click Apply locally → app relaunches")
    print(f"  6. On the login screen, choose:")
    print("     'Continuer avec Passerelle' → Claude Desktop + llm-relay")
    print("     'Se connecter à Anthropic'  → Claude Desktop standard")
    print()
    print("  ── Claude Code CLI ──")
    print()
    print("  To use Claude Code CLI through the proxy:")
    print(f"    export ANTHROPIC_BASE_URL={base_url}")
    print("    export ANTHROPIC_AUTH_TOKEN=any-value")
    print()
    print("  To use Claude Code CLI directly with Anthropic:")
    print("    export ANTHROPIC_BASE_URL=https://api.anthropic.com")
    print("    export ANTHROPIC_AUTH_TOKEN=<your-key>")
    print()
    print("  ── Switching modes ──")
    print()
    print("  If the login chooser doesn't appear, check:")
    print("    ~/Library/Application Support/Claude-3p/configLibrary/<id>.json")
    print("    Set 'disableDeploymentModeChooser' to false")
    print()
