"""
Session store.

Thread-safe, in-memory repository for conversation histories.

Each session maps a *response ID* (a unique string generated by the proxy
and returned to the client as ``"id"``) to the full list of OpenAI-compatible
message dicts that constitute that conversation's history.

Eviction policy
---------------
When the number of live sessions exceeds ``max_sessions``, the store drops
the *least-recently-used* sessions first (true LRU via ``OrderedDict``).
This is a deliberate improvement over a random/sort-by-key eviction strategy,
which could silently discard active sessions.

Thread safety
-------------
Every public method acquires ``self._lock`` before touching ``self._store``.
The lock is *not* re-entrant, so internal helpers that require the lock must
only be called while it is already held.
"""

from __future__ import annotations

import threading
from collections import OrderedDict
from typing import Optional


class SessionStore:
    """
    LRU in-memory store for per-session conversation histories.

    Usage::

        store = SessionStore(max_sessions=80, trim_to=20)

        # Persist a new or updated conversation.
        store.save("resp_abc123", messages)

        # Retrieve a previous conversation (returns None if unknown).
        history = store.get("resp_abc123")

        # Discard a session when it is no longer needed.
        store.delete("resp_abc123")
    """

    def __init__(self, max_sessions: int, trim_to: int) -> None:
        """
        Args:
            max_sessions: Maximum number of concurrent sessions.
                          When this limit is exceeded, old sessions are evicted.
            trim_to: Target size after an eviction sweep.
                     Must be strictly less than ``max_sessions`` to guarantee
                     that each eviction actually frees at least one slot.

        Raises:
            ValueError: If ``trim_to >= max_sessions``.
        """
        if trim_to >= max_sessions:
            raise ValueError(
                f"trim_to ({trim_to}) must be strictly less than "
                f"max_sessions ({max_sessions})"
            )

        self._max_sessions: int = max_sessions
        self._trim_to: int = trim_to

        # OrderedDict preserves insertion order, giving us O(1) LRU access:
        #   move_to_end(key)      → mark as most-recently-used
        #   popitem(last=False)   → evict the least-recently-used entry
        self._store: OrderedDict[str, list] = OrderedDict()
        self._lock: threading.Lock = threading.Lock()

    # ── Public API ────────────────────────────────────────────────────────────

    def get(self, session_id: str) -> Optional[list]:
        """
        Retrieve the message history for *session_id*.

        Accessing a session promotes it to most-recently-used so it
        is not the first candidate for eviction.

        Args:
            session_id: The response ID assigned by the proxy.

        Returns:
            A *copy* of the stored message list, or ``None`` if the session
            is unknown (expired, evicted, or never created).
        """
        with self._lock:
            if session_id not in self._store:
                return None

            # Promote to most-recently-used.
            self._store.move_to_end(session_id)

            # Return a shallow copy so callers cannot mutate the stored list.
            return list(self._store[session_id])

    def save(self, session_id: str, messages: list) -> None:
        """
        Persist *messages* under *session_id*, evicting stale sessions if needed.

        If *session_id* already exists, its history is overwritten and it is
        promoted to most-recently-used.

        Args:
            session_id: The response ID assigned by the proxy.
            messages: The full conversation history to store
                      (system message + all user/assistant turns so far).
        """
        with self._lock:
            # Store a shallow copy to decouple from the caller's list.
            self._store[session_id] = list(messages)
            self._store.move_to_end(session_id)
            self._evict_if_needed()

    def delete(self, session_id: str) -> None:
        """
        Remove *session_id* from the store.

        This is a no-op if the session does not exist (already expired or
        was never created).

        Args:
            session_id: The response ID to remove.
        """
        with self._lock:
            self._store.pop(session_id, None)

    def __len__(self) -> int:
        """Return the number of active sessions (thread-safe)."""
        with self._lock:
            return len(self._store)

    def __contains__(self, session_id: str) -> bool:
        """Support ``session_id in store`` checks (thread-safe)."""
        with self._lock:
            return session_id in self._store

    # ── Internal helpers ──────────────────────────────────────────────────────

    def _evict_if_needed(self) -> None:
        """
        Drop least-recently-used sessions until ``_store`` is within limits.

        Must be called while ``self._lock`` is already held — this method
        does *not* acquire the lock itself to avoid re-entrance issues.
        """
        if len(self._store) <= self._max_sessions:
            return

        # Calculate how many entries we must remove to reach trim_to.
        evict_count = len(self._store) - self._trim_to

        for _ in range(evict_count):
            if not self._store:
                break
            # popitem(last=False) removes the *oldest* (least-recently-used) entry.
            self._store.popitem(last=False)
